#!/bin/sh

# system startup.

# expand the ramdisk
/usr/bin/extract /ramfs.img /dev/ram0

# mount ramdisk, proc, sysfs
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

# load ext2
/sbin/insmod /lib/modules/mbcache.ko
/sbin/insmod /lib/modules/ext2.ko

# mount ramdisk
/bin/mount -t ext2 /dev/ram0 /var

# disable virtual console blanking
# /bin/echo -e '\033[9;0]\033[14;0]' > /dev/console

# enable the board leds
/bin/echo 20 > /sys/class/gpio/export
/bin/echo 21 > /sys/class/gpio/export
/bin/echo 22 > /sys/class/gpio/export

# set the board leds as output
/bin/echo out > /sys/class/gpio/gpio20/direction
/bin/echo out > /sys/class/gpio/gpio21/direction
/bin/echo out > /sys/class/gpio/gpio22/direction

# clear the board leds
/bin/echo 1 > /sys/class/gpio/gpio20/value
/bin/echo 1 > /sys/class/gpio/gpio21/value
/bin/echo 1 > /sys/class/gpio/gpio22/value

exit 0
